name: PR

on:
  pull_request:
    paths-ignore:
      - 'action/**'
      - 'action/*'

permissions:
  contents: read

env:
  RUSTC_WRAPPER: "sccache"

concurrency:
  group: "ci-pr-${{ github.event.number }}"
  cancel-in-progress: false

jobs:
  build:
    name: "Toolchain"
    uses: ./.github/workflows/job.build.yml
